version: '3.8'

services:
  # WhatsApp API Server for Local Testing
  whatsapp-api-local:
    build:
      context: ./go-whatsapp-web-multidevice-main
      dockerfile: ./docker/golang.Dockerfile
    container_name: whatsapp-api-local
    restart: unless-stopped
    ports:
      - "3000:3000"  # Expose port for local testing
    environment:
      - APP_PORT=3000
      - APP_DEBUG=true
      - APP_OS=Chrome
      - APP_BASIC_AUTH=  # No auth for local testing
      - DB_URI=file:storages/whatsapp.db?_foreign_keys=on
      - WHATSAPP_WEBHOOK=
      - WHATSAPP_WEBHOOK_SECRET=secret
      - WHATSAPP_AUTO_REPLY=
      - WHATSAPP_ACCOUNT_VALIDATION=true
      - WHATSAPP_CHAT_STORAGE=true
    volumes:
      - whatsapp_data_local:/app/storages
      - whatsapp_statics_local:/app/statics
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/app/devices"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  whatsapp_data_local:
    driver: local
  whatsapp_statics_local:
    driver: local
