version: '3.8'

services:
  whatsapp-api:
    image: aldinokemal2104/go-whatsapp-web-multidevice:latest
    container_name: whatsapp-api-vps
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - WHATSAPP_BASIC_AUTH=admin:hartonomotor123
      - WHATSAPP_WEBHOOK=https://hartonomotor.xyz/webhook/whatsapp
      - WHATSAPP_WEBHOOK_SECRET=hartonomotor_webhook_secret
      - APP_DEBUG=false
      - APP_OS=HartonoMotor
    volumes:
      - ./data:/app/storages
      - ./logs:/app/logs
    networks:
      - whatsapp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/app/devices"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  whatsapp-network:
    driver: bridge

volumes:
  whatsapp-data:
    driver: local
