services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hartono-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./public/build:/var/www/html/public/build
    networks:
      - hartono-network
    depends_on:
      - db
    user: root

  # Nginx Web Server
  webserver:
    image: nginx:alpine
    container_name: hartono-webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "8443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/ssl/:/etc/nginx/ssl/
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    networks:
      - hartono-network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: hartono-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - hartono-network

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hartono-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
    ports:
      - "8080:80"
    networks:
      - hartono-network
    depends_on:
      - db

  # WhatsApp API Service
  whatsapp-api:
    image: aldinokemal2104/go-whatsapp-web-multidevice:latest
    container_name: hartono-whatsapp-api
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - whatsapp_data:/app/storages
    environment:
      - APP_PORT=3000
      - APP_DEBUG=false
      - APP_OS=Hartono Motor
      - APP_WEBHOOK=${WHATSAPP_WEBHOOK_URL:-}
      - APP_BASIC_AUTH=${WHATSAPP_BASIC_AUTH:-admin:hartonomotor2024}
    command: ["rest"]
    networks:
      - hartono-network

  # WhatsApp API Service (VPS-Optimized)
  whatsapp-api:
    image: chrishubert/whatsapp-web-api:latest
    container_name: hartono-whatsapp-api
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - whatsapp_sessions:/app/session
      - whatsapp_logs:/app/session/message_log.txt
    environment:
      - API_KEY=hartonomotor2024
      - BASE_WEBHOOK_URL=http://app:80/api/whatsapp/webhook
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=false
      - MAX_ATTACHMENT_SIZE=10000000
      - SET_MESSAGES_AS_SEEN=true
      - DISABLED_CALLBACKS=
    networks:
      - hartono-network
    depends_on:
      - app

  # Certbot for SSL
  certbot:
    image: certbot/certbot
    container_name: hartono-certbot
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@hartonomotor.xyz --agree-tos --no-eff-email --force-renewal -d hartonomotor.xyz -d www.hartonomotor.xyz

networks:
  hartono-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  whatsapp_sessions:
    driver: local
  whatsapp_logs:
    driver: local
  whatsapp_data:
    driver: local
